export const plugs = [
		{
			"id": 58,
			"quote" : "I'm sorry. I lost my Macy Gray CD and I need caffeine.",
			"season" : "1",
			"episode" : "1",
			"timecode" : "2:17",
			"screengrab" : "assets/img/screens/s_macy_gray.jpg",
			"from" : "Rory Gilmore",
			"to" : "Lorelai Gilmore",
			"location" : "Luke's Diner",
			"description": "This is the first time we ever meet Rory. We don't know that she's Lorelai's daughter. They like the same music. It's cute. So we assume they're friends. Later around minute 32, Lorelai and Rory are fighting. When alone, both put on the same Macy Gray CD to sulk.",
			"refThumb" : "assets/img/refs/macygray.jpg",
			"refName" : "Macy Gray",
			"refIs" : "is a musician.",
			"refCategory" : "Music",
			"refYear1" : "1999",
			"refYear2" : "",
			"wikipedia" : "http://en.wikipedia.org/wiki/On_How_Life_Is",
			"images" : "https://www.google.com/search?q=macy+gray&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiljsnd5rfPAhVQzWMKHezaADsQ_AUICCgB&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=WEQ0l_m3Xm0",
			"refNotes" : ""
		},
		{ 
			"id": 100,
			"quote" : "RuPaul doesn't need this much makeup.",
			"season" : "1",
			"episode" : "1",
			"timecode" : "2:15",
			"screengrab" : "assets/img/screens/s_rupaul.jpg",
			"from" : "Rory Gilmore",
			"to" : "Lorelai Gilmore",
			"location" : "Luke's Diner",
			"description": "A spritely young woman sits down with Lorelai. They exchange sisterly banter. Are they sisters? Friends?",
			"refThumb" : "assets/img/refs/rupaul.jpg",
			"refName" : "RuPaul",
			"refIs" : "is a drag performer.",
			"refCategory" : "TV",
			"refYear1" : "1989-2000",
			"refYear2" : "",
			"wikipedia" : "http://en.wikipedia.org/wiki/RuPaul",
			"images" : "https://www.google.com/search?q=rupaul&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjD1OW95rfPAhVW9GMKHXbZCCMQ_AUICCgB&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=F4R0nHgwEBs",
			"refNotes" : "Although active in other mediums, RuPaul is listed as a \"TV\" because television brought his name to the masses and was most likely the way Rory would have come to know about him. RuPaul's first national exposure was in 1989 in The B-52's music video \"Love Shack\".",
		},
		{
			"id": 500,
			"quote" : "Look, Officer Krupke. She's right at that table, right over there.",
			"season" : "1",
			"episode" : "1",
			"timecode" : "2:33",
			"screengrab" : "assets/img/screens/s_officer_krupke.jpg",
			"from" : "Lorelai Gilmore",
			"to" : "Luke Danes",
			"location" : "Luke's Diner",
			"description": "Luke thinks Lorelai is trying to get more coffee for herself by saying it's for Rory. She mocks him, likening him to the the police officer character in West Side Story.",
			"refThumb" : "assets/img/refs/officerkrupke.jpg",
			"refName" : "Officer Krupke",
			"refIs" : "is a fictional character from West Side Story.",
			"refCategory" : "Film",
			"refYear1" : "1961",
			"refYear2" : "",
			"wikipedia" : "https://en.wikipedia.org/wiki/West_Side_Story",
			"images" : "https://www.google.com/search?q=officer+krupke&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwialP7n5rfPAhUNxmMKHf1BABoQ_AUIBygC",
			"video" : "https://www.youtube.com/watch?v=pq28qCklEHc",
			"refNotes" : "Although the play debuted in 1957, it's unlikely it ever toured Stars Hollow, so we are assuming Lorelei (and the majority of GG's audience) came to know of Officer Krupke through the 1961 film."
		},
		{
			"id": 7,
			"quote" : "For those of you who have not finished the final chapters of Huckleberry Finn you may use this time to do so.",
			"season" : "1",
			"episode" : "1",
			"timecode" : "8:16",
			"screengrab" : "assets/img/screens/s_huckleberry_fin.jpg",
			"from" : "Mrs. Traister",
			"to" : "other",
			"location" : "Stars Hollow High School",
			"description": "Girls around Rory try finger nail polish while she ignores them and writes her assignment. They are astonished at her nerdiness. Psht.",
			"refThumb" : "assets/img/refs/huckleberryfinn.jpg",
			"refName" : "Huckleberry Finn",
			"refIs" : "is an American novel.",
			"refCategory" : "Literature",
			"refYear1" : "1884",
			"refYear2" : "",
			"wikipedia" : "https://en.wikipedia.org/wiki/Huckleberry_Finn",
			"images" : "https://www.google.com/search?q=huckleberry+finn&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj35tzy5rfPAhVM1GMKHSVZD-gQ_AUIBigB",
			"video" : "https://www.youtube.com/watch?v=WXKgBIiP8IA",
			"refNotes" : ""
		},
		{
			"id": 808,
			"quote" : "Oh, well, there's no way Mark Twain can compete with that.",
			"season" : "2",
			"episode" : "3",
			"timecode" : "10:48",
			"screengrab" : "assets/img/screens/s_mark_twain.jpg",
			"from" : "Lane Kim",
			"to" : "Rory Gilmore",
			"location" : "Kim's Antiques",
			"description": "Refers to prior scene in school. Mark Twain is being compared to glittery nail polish that smells like bubblegum when it dries. Naturally.",
			"refThumb" : "assets/img/refs/markTwain.jpg",
			"refName" : "Mark Twain",
			"refIs" : "is an American writer.",
			"refCategory" : "Literature",
			"refYear1" : "1835",
			"refYear2": "1910",
			"wikipedia" : "https://en.wikipedia.org/wiki/Mark_twain",
			"images" : "https://www.google.com/search?q=mark+twain&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjhj7f75rfPAhUM-GMKHbelB8MQ_AUIBigB",
			"video" : "https://www.youtube.com/watch?v=opuF_jtobNA",
			"refNotes" : ""
		},
		{
			"id": 9,
			"quote" : "I'm gonna be in a Britney Spears video?",
			"season" : "2",
			"episode" : "9",
			"timecode" : "14:11",
			"screengrab" : "assets/img/screens/s_britney_spears.jpg",
			"from" : "Rory Gilmore",
			"to" : "Lorelai Gilmore",
			"location" : "Independence Inn",
			"description": "Upon receiving a plaid skirt as a gift from her mother. Shortly thereafter she finds out she will be attending a private school called Chilton. Hooray!",
			"refThumb" : "assets/img/refs/britneySpears.jpg",
			"refName" : "Britney Spears",
			"refIs" : "is a pop singer.",
			"refCategory" : "Music",
			"refYear1" : "1999",
			"refYear2": "now",
			"wikipedia" : "https://en.wikipedia.org/wiki/Britney_Spears",
			"images" : "https://www.google.com/search?q=britney+spears&espv=2&biw=1278&bih=708&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjwiK_Iz7PPAhVGVWMKHQMaAPQQ_AUICCgD",
			"video" : "https://www.youtube.com/watch?v=C-u5WLJ9Yk4",
			"refNotes" : "First album (\"...Baby One More Time\")released in 1999."
		},
		{
			"id": 74,
			"quote" : "Sookie, there are several chapters from a Stephen King novel I'd reenact before I'd resort to that option.",
			"season" : "3",
			"episode" : "7",
			"timecode" : "17:19",
			"screengrab" : "assets/img/screens/s_stephen_king.jpg", 
			"from" : "Lorelai Gilmore",
			"to" : "Sookie St. James",
			"location" : "Lorelai's House",
			"description": "Lorelai is trying to figure out how to afford the enrollment fee for Chilton. Sookie suggests she call her parents for help. This is the first we've heard of them.",
			"refThumb" : "assets/img/refs/stephenKing.jpg",
			"refName" : "Stephen King",
			"refIs" : "is an American horror/sci-fi novelist.",
			"refCategory" : "Literature",
			"refYear1" : "1973",
			"refYear2": "now",
			"wikipedia" : "https://en.wikipedia.org/wiki/Stephen_King",
			"images" : "https://www.google.com/search?q=stephen+king&biw=1338&bih=766&tbm=isch&source=lnms&sa=X&ved=0ahUKEwjHnYSY5bfPAhVU8WMKHf_yCl0Q_AUIBygC",
			"video" : "https://www.youtube.com/watch?v=bW3zOhqTW2U",
			"refNotes" : "Born in 1947, first novel (\"Carrie\") released in 1973.."
		},
		{
			"id": 52,
			"quote" : "It's at Zsa Zsa Gabor's house.",
			"season" : "3",
			"episode" : "2",
			"timecode" : "18:01",
			"screengrab" : "assets/img/screens/s_zsa_zsa_gabor.jpg", 
			"from" : "Lorelai Gilmore",
			"to" : "Sookie St. James",
			"location" : "Lorelai's House",
			"description": "A lightning quick reply to Sookie's question from the kitchen \"Where's your pate?\"",
			"refThumb" : "assets/img/refs/zsazsa.jpg",
			"refName" : "Zsa Zsa Gabor",
			"refIs" : "is a film actress.",
			"refCategory" : "Film",
			"refYear1" : "1934", 
			"refYear2": "now",
			"wikipedia" : "https://en.wikipedia.org/wiki/Zsa_Zsa_Gabor",
			"images" : "https://www.google.com/search?q=zsa+zsa+gabor&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiYy96bjrrPAhVEbT4KHX1ZDAQQ_AUICSgC&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=VdYuRZ_iEVQ",
			"refNotes" : "Zsa Zsa's first stage appearance was in the opera \"Der singende Traum (The Singing Dream)\" in 1934."
		},
		{
			"id": 53,
			"quote" : "God! You're just like Ruth Gordon just standing there with a tannis root. Make a noise.",
			"season" : "3",
			"episode" : "1",
			"timecode" : "23:07",
			"screengrab" : "assets/img/screens/s_ruth_gordon.jpg", 
			"from" : "Rory Gilmore",
			"to" : "Dean Forester",
			"location" : "Stars Hollow High School",
			"description": "Rory spills her books and (gasp) meets her first crush. As luck would have it (gasp) he gets the reference to Rosemary's Baby.",
			"refThumb" : "assets/img/refs/ruthGordon.jpg",
			"refName" : "Ruth Gordon",
			"refIs" : "is an actress.",
			"refCategory" : "Film",
			"refYear1" : "1968", 
			"refYear2": "1985",
			"wikipedia" : "http://en.wikipedia.org/wiki/Ruth_Gordon",
			"images" : "https://www.google.com/search?q=ruth+gordon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjZ-9OSkLrPAhXGNz4KHaBcAmgQ_AUICCgB&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=QlSgzo3vG6Y&list=PLs6luI3JdPoGc_zlCWGP4j8vMKS0nXSUa",
			"refNotes" : ""
		},
		{
			"id": 44,
			"quote" : "Rosemary's Baby.",
			"season" : "4",
			"episode" : "8",
			"timecode" : "23:13",
			"screengrab" : "assets/img/screens/s_rosemarys_baby.jpg", 
			"from" : "Dean Forester",
			"to" : "Rory Gilmore",
			"location" : "Stars Hollow High School",
			"description": "A handsome young buck surprises Rory by catching her reference to a 60s horror film - and then throwing back a compliment. Le gasp.",
			"refThumb" : "assets/img/refs/rosemarys_baby.jpg",
			"refName" : "Rosemary's Baby",
			"refIs" : "is a horror film.",
			"refCategory" : "Film",
			"refYear1" : "1968", 
			"refYear2": "",
			"wikipedia" : "https://en.wikipedia.org/wiki/Rosemary%27s_Baby_(film)",
			"images" : "https://www.google.com/search?q=rosemary%27s+baby&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwii6Ju9kLrPAhUFNT4KHTH9CGcQ_AUIBigB",
			"video" : "https://www.youtube.com/watch?v=PewtQsgN5uo",
			"refNotes" : ""
		},
		{
			"id": 99,
			"quote" : "Chicago. Windy. Oprah.",
			"season" : "4",
			"episode" : "5",
			"timecode" : "23:36",
			"screengrab" : "assets/img/screens/s_oprah.png",
			"from" : "Rory Gilmore",
			"to" : "Dean Forester",
			"location" : "Stars Hollow High School",
			"description": "Rory's flirting skills at their maximum. Dean tells her that his family just moved to Stars Hollow from Chicago. ",
			"refThumb" : "assets/img/refs/oprah.jpg",
			"refName" : "Oprah",
			"refIs" : "Oprah (Winfrey) is a popular talk show host.",
			"refCategory" : "TV",
			"refYear1" : "1986",
			"refYear2": "now",
			"wikipedia" : "http://en.wikipedia.org/wiki/Oprah_Winfrey",
			"images" : "https://www.google.com/search?q=oprah+winfrey&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjYja6KkbrPAhVKdD4KHZmYCx4Q_AUICSgC&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=qHajE73F0BU",
			"refNotes" : "Oprah Winfrey is best known for her talk show, which aired for the first time in 1986 and was filmed in Chicago."
		},
		{
			"id": 98,
			"quote" : "So, how are you liking Moby Dick?",
			"season" : "4",
			"episode" : "2",
			"timecode" : "25:44",
			"screengrab" : "assets/img/screens/s_moby_dick.jpg", 
			"from" : "Dean Forester",
			"to" : "Rory Gilmore",
			"location" : "Town Square",
			"description": "Dear Dean has just subtly let Rory know that he has paid attention to her reading habits. Smooth.",
			"refThumb" : "assets/img/refs/moby_dick.jpg",
			"refName" : "Moby Dick",
			"refIs" : "is a novel.",
			"refCategory" : "Literature",
			"refYear1" : "1851",  
			"refYear2": "now",
			"wikipedia" : "http://en.wikipedia.org/wiki/Moby-Dick",
			"images" : "https://www.google.com/search?q=moby+dick&source=lnms&tbm=isch&sa=X&ved=0ahUKEwicjaWGkrrPAhUCET4KHZS4Cp4Q_AUICSgC",
			"video" : "https://www.youtube.com/watch?v=lZ6NEHDgk58",
			"refNotes" : ""
		},
		{
			"id": 96,
			"quote" : "It's my first Melville.",
			"season" : "5",
			"episode" : "7",
			"timecode" : "25:48",
			"screengrab" : "assets/img/screens/s_melville.jpg", 
			"from" : "Rory Gilmore",
			"to" : "Dean Forester",
			"location" : "Town Square",
			"description": "You never forget your first love, erm...Melville. Rory gives us a glimpse at how much of a book worm she really is. ",
			"refThumb" : "assets/img/refs/herman_melville.jpg",
			"refName" : "Melville",
			"refIs" : "(Herman) Melville was a novelist, famous for writing \"Moby Dick.\"",
			"refCategory" : "Literature",
			"refYear1" : "1845", 
			"refYear2": "1891",
			"wikipedia" : "http://en.wikipedia.org/wiki/Herman_Melville",
			"images" : "https://www.google.com/search?q=herman+melville&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjlw_zQkrrPAhVKdD4KHZmYCx4Q_AUICSgC&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=AlakuImJ8Ys",
			"refNotes" : "Melville's first novel (\"Typee\") was published in 1845."
		},
		{
			"id": 13,
			"quote" : "Last week it was Madame Bovary.",
			"season" : "5",
			"episode" : "8",
			"timecode" : "26:18",
			"screengrab" : "assets/img/screens/s_madame_bovary.jpg", 
			"from" : "Dean Forester",
			"to" : "Rory Gilmore",
			"location" : "Town Square",
			"description": "Dean reveals he's been watching Rory. Of course, not in a \"...creepy, like I'm watching you sort of way,\" but because she's \"nice to look at,\" and has \"unbelievable concentration.\" MmHmm.",
			"refThumb" : "assets/img/refs/madame_bovary.jpg",
			"refName" : "Madame Bovary",
			"refIs" : "a french realist novel by Gustave Flaubert published in 1856.",
			"refCategory" : "Literature",
			"refYear1" : "1856",  
			"refYear2": "",
			"wikipedia" : "http://en.wikipedia.org/wiki/Madame_Bovary",
			"images" : "https://www.google.com/search?q=madame+bovary&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjo0uiHk7rPAhWDWT4KHXTNCUMQ_AUICCgD",
			"video" : "https://www.youtube.com/watch?v=4ICkjNbTCgQ",
			"refNotes" : ""
		},
		{
			"id": 101,
			"quote" : "You're gonna have to turn into Flo-Jo to get away from me.",
			"season" : "5",
			"episode" : "1",
			"timecode" : "30:09",
			"screengrab" : "assets/img/screens/s_flo_jo.jpg", 
			"from" : "Lorelai Gilmore",
			"to" : "Rory Gilmore",
			"location" : "Town Square",
			"description": "Remember when earlier in the episode Rory said she sucked at sports? Heh heh.",
			"refThumb" : "assets/img/refs/flojo.jpg",
			"refName" : "Flo-Jo",
			"refIs" : "(Florence Griffith Joyner) was an American Olympic track star.",
			"refCategory" : "Sports",
			"refYear1" : "1988",  
			"refYear2": "1998",
			"wikipedia" : "http://en.wikipedia.org/wiki/Florence_Griffith_Joyner",
			"images" : "https://www.google.com/search?q=madame+bovary&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjo0uiHk7rPAhWDWT4KHXTNCUMQ_AUICCgD#tbm=isch&q=flo+jo",
			"video" : "https://www.youtube.com/watch?v=UvOtNW4JRwA",
			"refNotes" : "\"Flo Jo\" was a nickname for Florence Griffith Joyner during the 1988 Summer Olympic Games. Although active in the sport prior to 1988, she was not a household name until her record setting performance in that year."
		},
		{
			"id": 103,
			"quote" : "You're not going to give me the \"Mommie Dearest\" treatment forever, are ya?",
			"season" : "6",
			"episode" : "4",
			"timecode" : "33:57",
			"screengrab" : "assets/img/screens/s_mommy_dearest.jpg", 
			"from" : "Lorelai Gilmore",
			"to" : "Rory Gilmore",
			"location" : "Independence Inn",
			"description": "Lorelai wants to know when she will no longer be the villain in Rory's version of the present. Then again, she did just try to trick Rory back into being friends by offering her a few hours of work at the Inn \"for extra cash.\" Nice try, mom.",
			"refThumb" : "assets/img/refs/mommie_dearest.jpg",
			"refName" : "Mommie Dearest",
			"refIs" : "is a memoir and dramatic film.",
			"refCategory" : "Film",
			"refYear1" : "1981", 
			"refYear2": "", 
			"wikipedia" : "https://en.wikipedia.org/wiki/Mommie_Dearest",
			"images" : "https://www.google.com/search?q=madame+bovary&espv=2&biw=1338&bih=766&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjo0uiHk7rPAhWDWT4KHXTNCUMQ_AUICCgD#tbm=isch&q=mommie+dearest",
			"video" : "https://www.youtube.com/watch?v=tUkE9qaVgmo",
			"refNotes" : "In \"Mommy Dearest,\" the lead character (based on the real-life actress Joan Crawford) is an abusive mother."
		},
		{
			"id": 102,
			"quote" : "So do we go in or do we just stand here reenacting \"The Little Match Girl?\"",
			"season" : "6",
			"episode" : "2",
			"timecode" : "34:29",
			"screengrab" : "assets/img/screens/s_little_match_girl.jpg", 
			"from" : "Rory Gilmore",
			"to" : "Lorelai Gilmore",
			"location" : "The Gilmore House",
			"description": "Lorelai is having trouble knocking on the door for the dreaded off-holiday dinner with her parental unit. ",
			"refThumb" : "assets/img/refs/matchgirl.png",
			"refName" : "The Little Match Girl",
			"refIs" : "is a short story by Hans Christen Anderson.",
			"refCategory" : "Literature",
			"refYear1" : "1845", 
			"refYear2": "", 
			"wikipedia" : "http://en.wikipedia.org/wiki/The_Little_Match_Girl",
			"images" : "https://www.google.com/search?q=the+little+match+girl&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj09OqBlbrPAhVEaD4KHRXcDgkQ_AUICSgC&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=_Kku_XW4krg",
			"refNotes" : "In the story \"The Little Match Girl,\" a scared little girl avoids going home because she is afraid of her father."
		},
		{
			"id": 93,
			"quote" : "Okay, look, I know you and me are having a thing here and I know you hate me but I need you to be civil - at least through dinner – and then on the way home you can pull a Menendez.",
			"season" : "6",
			"episode" : "6",
			"timecode" : "34:39",
			"screengrab" : "assets/img/screens/s_menendez_bros.jpg", 
			"from" : "Lorelai Gilmore",
			"to" : "Rory Gilmore",
			"location" : "The Gilmore House",
			"description": "Lorelai asks for a truce in exchange for the opportunity for Rory to murder her later. Ah, parenting.",
			"refThumb" : "assets/img/refs/menendez_bros.jpg",
			"refName" : "Menendez",
			"refIs" : "(brothers) were siblings convicted of killing their parents.",
			"refCategory" : "News",
			"refYear1" : "1994", 
			"refYear2": "", 
			"wikipedia" : "http://en.wikipedia.org/wiki/Lyle_and_Erik_Menendez",
			"images" : "https://www.google.com/search?q=menendez+brothers&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj-9oeylbrPAhVFND4KHXdGDn0Q_AUICCgB&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=cltnL2fsyOs",
			"refNotes" : ""
		},
		{
			"id": 10,
			"quote" : "We're thinking of having her studied at M.I.T.",
			"season" : "7",
			"episode" : "7",
			"timecode" : "35:38",
			"screengrab" : "assets/img/screens/s_mit.jpg", 
			"from" : "Lorelai Gilmore",
			"to" : "Richard Gilmore",
			"location" : "The Gilmore House",
			"description": "Because she's tall. She's 5'7. That's tall. Lorelai, you're daughter's tall. A few minutes later in the episode, as the two are leaving, Lorelai asks Rory \"Do I look shorter, because I feel shorter.\" A classic GG writer move.",
			"refThumb" : "assets/img/refs/mit.png",
			"refName" : "M.I.T.",
			"refIs" : "(Massachusetts Institute of Technology) is a university well-known for its scientific research.",
			"refCategory" : "Institution",
			"refYear1" : "1861", 
			"refYear2": "2000", 
			"wikipedia" : "http://en.wikipedia.org/wiki/Massachusetts_Institute_of_Technology",
			"images" : "https://www.google.com/search?q=mit&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjCoNfblbrPAhWBZj4KHdxhCacQ_AUICigD&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=u0SFyokPoBk",
			"refNotes" : ""
		},
		{
			"id": 86,
			"quote" : "That's so Nick at Night.",
			"season" : "7",
			"episode" : "9",
			"timecode" : "42:34",
			"screengrab" : "assets/img/screens/s_nick_at_night.jpg", 
			"from" : "Rory Gilmore",
			"to" : "Lorelai Gilmore",
			"location" : "Luke's Diner",
			"description": "Mom wants to know about the boy. Mom wants to know if he's \"dreamy.\"",
			"refThumb" : "assets/img/refs/nickatnight.jpg",
			"refName" : "Nick at Night",
			"refIs" : "is a television program that features old TV shows.",
			"refCategory" : "TV",
			"refYear1" : "1985", 
			"refYear2": "now", 
			"wikipedia" : "http://en.wikipedia.org/wiki/Nick_at_Nite",
			"images" : "https://www.google.com/search?q=nick+at+night&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjMgvSylrrPAhWMdD4KHXFRA1YQ_AUICSgC&biw=1338&bih=766",
			"video" : "https://www.youtube.com/watch?v=_R78N_K0FyA",
			"refNotes" : "Shows aired at that time would have included \"I Love Lucy,\" \"The Dick Van Dike Show\", \"Bewitched,\" and more."
		}
	];
